/**
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * HpcsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_HpcsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_HpcsApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/HPC.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  HpcsApi 
{
public:

    explicit HpcsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~HpcsApi();

    /// <summary>
    /// Get information of a specific HPC
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id"></param>
    pplx::task<std::shared_ptr<HPC>> getHPCById(
        utility::string_t id
    ) const;
    /// <summary>
    /// List all HPCs
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<HPC>>> listHPCs(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_HpcsApi_H_ */

